name: GitActions-Demo3
on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
      - name: Report current time
        run:
          echo "this workflow ran on a schedule"
          echo "current UTC time:$(date -u)"
          echo "current local time (on runner):$(date)"
